<?php

namespace AppBundle\Repository;

/**
 * data_urlop_lekarzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class data_urlop_lekarzRepository extends \Doctrine\ORM\EntityRepository
{
}
