<?php

namespace AppBundle\Repository;

/**
 * data_urlopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class data_urlopRepository extends \Doctrine\ORM\EntityRepository
{
}
