<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * data_urlopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class data_urlopRepository extends \Doctrine\ORM\EntityRepository
{
/*    public function getUserUrlops(User $user){
        $qb=$this->createQueryBuilder('data_urlop');
        $qb->leftJoin('data_urlop.lekarze','lekarze')
            ->where('lekarze.id = :userLekarzId')
            ->setParameter('userLekarzId',$user->getIdLekarz());
        return $qb->getQuery()->getResult();
    }
*/
    public function getUserDataUrlops(User $user, \DateTime $start, \DateTime $end){

        $q=$this->getEntityManager()->createQuery('
        SELECT data_urlop
        FROM AppBundle:data_urlop data_urlop
        LEFT JOIN data_urlop.lekarze lekarze
        WHERE lekarze.id = :userLekarzId
        AND data_urlop.data
        BETWEEN :startData AND :endData
        ')  ->setParameter('userLekarzId',$user->getIdLekarz())
            ->setParameter('startData',date_format($start,'Y-m-d'))
            ->setParameter('endData',date_format($end,'Y-m-d'))
            ->getResult();

        return $q;
    }
    public function getDataUrlopByData(\DateTime $start, \DateTime $end){
        $q=$this->getEntityManager()->createQuery('
        SELECT data_urlop
        FROM AppBundle:data_urlop data_urlop
        WHERE data_urlop.data BETWEEN :startDate AND :endDate
        ')->setParameter('startDate',$start->format('Y-m-d'))
        ->setParameter('endDate',$end->format('Y-m-d'))
        ->getResult();
        return $q;
    }

    public function getDataUrlopByIdLekarz($idLekarz, \DateTime $start, \DateTime $end){

        $q=$this->getEntityManager()->createQuery('
        SELECT data_urlop
        FROM AppBundle:data_urlop data_urlop
        LEFT JOIN data_urlop.lekarze lekarze
        WHERE lekarze.id = :idLekarz
        AND data_urlop.data
        BETWEEN :startData AND :endData
        ')  ->setParameter('idLekarz',$idLekarz)
            ->setParameter('startData',date_format($start,'Y-m-d'))
            ->setParameter('endData',date_format($end,'Y-m-d'))
            ->getResult();

        return $q;
    }
}
