<?php

namespace AppBundle\Repository;

/**
 * godz_przyjRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class godz_przyjRepository extends \Doctrine\ORM\EntityRepository
{
}
