<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * lekarz_godz_przyjRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lekarz_godz_przyjRepository extends \Doctrine\ORM\EntityRepository
{

    public function getUserLekarzGodzPrzyj(User $user){
        $query=$this->getEntityManager()->createQuery('
        SELECT lekarzGodzPrzyj
        FROM AppBundle:lekarz_godz_przyj AS lekarzGodzPrzyj
        WHERE lekarzGodzPrzyj.idLekarz = :userIdLekarz
        ')->setParameter('userIdLekarz',$user->getIdLekarz())
        ->getResult();
        return $query;
    }

    public function getLekarzGodzPrzyjById(int $id){

    }


}
