<?php

namespace AppBundle\Repository;
use AppBundle\Entity\lekarz;
use AppBundle\Entity\User;

/**
 * lekarz_godz_przyjRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lekarz_godz_przyjRepository extends \Doctrine\ORM\EntityRepository
{

    public function getUserLekarzGodzPrzyj(User $user){
        $query=$this->getEntityManager()->createQuery('
        SELECT lekarzGodzPrzyj
        FROM AppBundle:lekarz_godz_przyj AS lekarzGodzPrzyj
        WHERE lekarzGodzPrzyj.idLekarz = :userIdLekarz
        ')->setParameter('userIdLekarz',$user->getIdLekarz())
        ->getResult();
        return $query;
    }

    public function getUserLekarzGodzPrzyjById(User $user, int $idGodzPrzyj){
        $query=$this->getEntityManager()->createQuery('
        SELECT lekarzGodzPrzyj
        FROM AppBundle:lekarz_godz_przyj AS lekarzGodzPrzyj
        WHERE lekarzGodzPrzyj.idLekarz = :userIdLekarz
        AND lekarzGodzPrzyj.id = :idGodzPrzyj
        ')->setParameter('userIdLekarz',$user->getIdLekarz())
            ->setParameter('idGodzPrzyj',$idGodzPrzyj)
            ->getResult();
        return $query;
    }

    public function getActiveLekarzGodzPrzyjByIdLekarz($lekarz){
        $query=$this->getEntityManager()->createQuery('
        SELECT lekarzGodzPrzyj
        FROM AppBundle:lekarz_godz_przyj AS lekarzGodzPrzyj
        WHERE lekarzGodzPrzyj.idLekarz = :idLekarz
        AND lekarzGodzPrzyj.aktywna = :t
        ')->setParameter('idLekarz',$lekarz)
            ->setParameter('t',true)
            ->getResult();
        return $query;
    }


}
