<?php

namespace AppBundle\Repository;

/**
 * lekarz_urlopyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lekarz_urlopyRepository extends \Doctrine\ORM\EntityRepository
{
}
