<?php

namespace AppBundle\Repository;

/**
 * lekarz_godz_przyjRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lekarz_godz_przyjRepository extends \Doctrine\ORM\EntityRepository
{
}
