<?php

namespace AppBundle\Repository;

/**
 * lekarzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lekarzRepository extends \Doctrine\ORM\EntityRepository
{
}
