<?php

namespace AppBundle\Repository;

/**
 * pacjentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pacjentRepository extends \Doctrine\ORM\EntityRepository
{
}
