<?php

namespace AppBundle\Repository;

/**
 * specjalizacjaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class specjalizacjaRepository extends \Doctrine\ORM\EntityRepository
{
}
