<?php

namespace AppBundle\Repository;
use AppBundle\Entity\wizyta;

/**
 * wizytaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class wizytaRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEventsByDate($start, $end, $type='all'){
        $q=$this->getEntityManager()->createQuery('
        SELECT events FROM AppBundle:wizyta events
        WHERE events.data
        BETWEEN :startData AND :endData
        ')
            ->setParameter('startData',$start)
            ->setParameter('endData',$end)
            ->getResult();
        return $q;
    }
}
